### ISSUE TITLE
Optimization of Retina - pixelGrid

### ISSUE THREAD

**Issue by wlord01** [wlord01/GiovanniIlariaWilliam#1]
* Try to optimize method "pixelGrid" in class "Retina" by use of broadcasting instead of for loop.

**Comment by wlord01** [comment]
I realized this was different to what I initially thought so broadcasting is not an option. There might be other solutions though. @mefit0 and I discussed this and maybe it's better to go on with the other features of the project before optimizing. Anyhow, when optimizing, one idea is to use numpy linspace and meshgrid and use the coordinate points as pixels instead of squares. This probably makes the simulation faster, but with this solution we would also have to change the code that generates figures.

**Comment by mefit0** [comment]
I totally agree; let's go on with the simulation for now and see what will happen when it has to check if the environment = goal. If it will be too slow, it could be worth a try to do as you brilliantly suggested :)
