### ISSUE TITLE
Changing the environment and retina size

### ISSUE THREAD

**Issue by wlord01** [wlord01/GiovanniIlariaWilliam#7]
After talking to Gianluca today, we should use a smaller retina size and spread out the initial positioning of the polygons for now. This is to make sure the retina can only see one polygon (i.e. sub-goal) at any one time. With this done, we can work on the goal-classifier functions and the parameterised skill.

**Comment by mefit0** [comment]
So, should we have a retina big as the figures or maybe even smaller? (we'll still have to worry about this when the figures will be close or overlapping...)

**Comment by wlord01** [comment]
Gianluca said a retina twice the size of the figures is a good choice for now. Yes indeed, we will have to deal with these problems later.
